---
commitizen:
  allow_abort: true
  annotated_tag: true
  gpg_sign: true
  major_version_zero: true
  name: cz_conventional_commits
  tag_format: $version
  update_changelog_on_bump: true
  version: 0.1.1
  version_files:
  - lua/metrostroi/extensions/version.lua:MEL.Version
  version_scheme: semver
