repos:
- hooks:
  - id: check-vcs-permalinks
  - args:
    - --markdown-linebreak-ext=md
    id: trailing-whitespace
  - id: check-yaml
  - id: end-of-file-fixer
  - id: trailing-whitespace
  - id: check-executables-have-shebangs
  - id: check-json
  - id: detect-private-key
  - id: forbid-submodules
  repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.6.0
- hooks:
  - id: commitizen
  - id: commitizen-branch
    stages:
    - push
  repo: https://github.com/commitizen-tools/commitizen
  rev: v3.27.0
